#!/usr/bin/env python3

# This Python file uses the following encoding: utf-8
import sys
import os.path
from KMixTest import start_kmixtest

# Starting point of execution
if __name__ == "__main__":
    if len(sys.argv) == 1:
        start_kmixtest()
    elif len(sys.argv) == 2:
        if os.path.isfile(sys.argv[1]):
            start_kmixtest(load_filename=sys.argv[1])
        else:
            start_kmixtest()


# import sys
# from PySide2.QtCore import *
# from PySide2.QtWidgets import *
# from PySide2.QtGui import *
# from PySide2.QtPrintSupport import *
# from PySide2.QtUiTools import *
# from sys import exit
# from time import time,sleep
# from enum import Enum,IntEnum,auto,unique
# from os import cpu_count
# from queue import Queue, Empty
# import signal

